### ISSUE TITLE
installing m2e-connector for antrun fails on mars 

### ISSUE THREAD

**Issue by ufkub** [mwensveen-nl/nl-mwensveen-m2e-extras#6]
Tried to install the m2e connector for AntRun on Eclipse Mars.
Installed is: plugins/org.eclipse.core.resources_3.10.0.v20150423-0755.jar
But AntRun connector claims to be compatible with org.eclipse.core.resources [3.9.0,3.10.0)

Failure message:

Cannot complete the install because one or more required items could not be found.
  Software being installed: m2e Connector for AntRun 2.1.0 (nl.mwensveen.m2e.extras.antrun.feature.feature.group 2.1.0)
  Missing requirement: m2e connector for AntRun 2.1.0 (nl.mwensveen.m2e.extras.antrun 2.1.0) requires 'bundle org.eclipse.core.resources [3.9.0,3.10.0)' but it could not be found
  Cannot satisfy dependency:
    From: m2e Connector for AntRun 2.1.0 (nl.mwensveen.m2e.extras.antrun.feature.feature.group 2.1.0)
    To: nl.mwensveen.m2e.extras.antrun [2.1.0]

**Comment by mwensveen-nl** [comment]
Updated the m2e connectors to be compatible with Mars and m2e 1.6

**Comment by ufkub** [comment]
Tested. Works. Thank you.
